module.exports = {
    SET_SOCKET: 'SET_SOCKET',
    SET_NICKNAME: 'SET_NICKNAME',
    VERIFIY_USER: 'VERIFIY_USER',
    SET_ERROR: 'SET_ERROR',
    CREATE_USER: 'CREATE_USER',
    TYPING: 'TYPING',
    RECIVE_TYPING: 'RECIVE_TYPING',
    SET_TYPING: 'SET_TYPING',
    SET_MESSAGE: 'SET_MESSAGE',
    SEND_MESSAGE: 'SEND_MESSAGE',
    RECIVE_MESSAGE: 'RECIVE_MESSAGE',
    SEND_PMESSAGE: 'SEND_PMESSAGE',
    RECIVE_PMESSAGE: 'RECIVE_PMESSAGE',
    RECIVE_ONLINE: 'RECIVE_ONLINE',
    UPDATE_USERS: 'UPDATE_USERS',
    CHAT_WITH: 'CHAT_WITH'
}