module.exports = {
    SET_SOCKET: 'SET_SOCKET',
    SET_NICKNAME: 'SET_NICKNAME',
    VERIFIY_USER: 'VERIFIY_USER',
    SET_ERROR: 'SET_ERROR',
    CREATE_USER: 'CREATE_USER',
    SEND_MESSAGE: 'SEND_MESSAGE',
    TYPING: 'TYPING',
    RECIVE_TYPING: 'RECIVE_TYPING',
    SET_TYPING: 'SET_TYPING',
    SET_MESSAGE: 'SET_MESSAGE',
    RECIVE_MESSAGE: 'RECIVE_MESSAGE'
}